name: CodSpeed Benchmarks

on:
  push:
    branches:
      - "main"
  pull_request:
    types: ["opened", "reopened", "synchronize"]

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bench:
          - parser
          - visit_compare
          - semantic
    steps:
      - uses: actions/checkout@v6

      - name: Setup rust toolchain, cache and cargo-codspeed binary
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install cargo-codspeed
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-codspeed

      - name: Build benchmark
        run: cargo codspeed build --bench ${{ matrix.bench }}

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v4
        with:
          token: ${{ secrets.CODSPEED_TOKEN }}
          mode: simulation
          run: cargo codspeed run
